=== buttonwood-protocol/buttonwood-protocol-list/src/protocol-definition.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://buttonwood-protocol.github.io/buttonwood-protocol-list/src/protocol-definition.schema.json",
  "title": "Protocol Definition",
  "description": "Schema for protocol data supplied to build a ProtocolList",
  "definitions": {
    "Address": {
      "type": "string",
      "description": "The checksummed address on the specified chain ID",
      "pattern": "^0x[a-fA-F0-9]{40}$",
      "examples": [
        "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
      ]
    },
    "Name": {
      "type": "string",
      "description": "The name of this address or protocol",
      "minLength": 1,
      "maxLength": 40,
      "examples": [
        "Buttonwood"
      ]
    },
    "ImageURI": {
      "type": "string",
      "description": "A URI for an image to associate with this address or protocol. Recommend SVG or PNG of size 256x256",
      "oneOf": [
        {
          "format": "uri"
        },
        {
          "pattern": "^assets/"
        }
      ],
      "examples": [
        "ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM",
        "assets/protocols/ampleforth/logo.png"
      ]
    },
    "Homepage": {
      "type": "string",
      "description": "A URI for a website to associate with this address or protocol",
      "format": "uri",
      "examples": [
        "https://button.foundation/"
      ]
    },
    "ProtocolAddressInfo": {
      "type": "object",
      "description": "Metadata for a protocol controlled address",
      "properties": {
        "name": {
          "$ref": "#/definitions/Name"
        },
        "imageURI": {
          "$ref": "#/definitions/ImageURI"
        },
        "homepage": {
          "$ref": "#/definitions/Homepage"
        }
      },
      "additionalProperties": false
    },
    "ProtocolChainInfo": {
      "type": "object",
      "properties": {
        "auctionCreators": {
          "type": "array",
          "description": "An array of addresses that are controlled by the protocol and used to create auctions on this chain",
          "items": {
            "$ref": "#/definitions/Address"
          },
          "maxItems": 1000,
          "examples": [
            "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
          ]
        },
        "bondCreators": {
          "type": "array",
          "description": "An array of addresses that are controlled by the protocol and used to create bonds on this chain",
          "items": {
            "$ref": "#/definitions/Address"
          },
          "maxItems": 1000,
          "examples": [
            "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
          ]
        }
      },
      "additionalProperties": false
    }
  },
  "type": "object",
  "properties": {
    "name": {
      "$ref": "#/definitions/Name"
    },
    "imageURI": {
      "$ref": "#/definitions/ImageURI"
    },
    "homepage": {
      "$ref": "#/definitions/Homepage"
    },
    "chains": {
      "type": "object",
      "description": "A map of the chain name to the protocol data related to that chain. We use chain name here to reduce potential for error, as it is easier to mix up numerical chain IDs than it is a chain name",
      "propertyNames": {
        "enum": [
          "mainnet",
          "goerli"
        ]
      },
      "patternProperties": {
        "": {
          "$ref": "#/definitions/ProtocolChainInfo"
        }
      }
    },
    "overrides": {
      "type": "object",
      "description": "A map of an address specified in ProtocolChainInfo to properties that override the base protocol metadata",
      "propertyNames": {
        "$ref": "#/definitions/Address"
      },
      "patternProperties": {
        "": {
          "$ref": "#/definitions/ProtocolAddressInfo"
        }
      }
    }
  },
  "required": [
    "name",
    "chains"
  ],
  "additionalProperties": false
}

=== buttonwood-protocol/buttonwood-protocol-list/src/protocolDefinitions/ampleforth.json
{
  "name": "Ampleforth",
  "homepage": "https://www.ampleforth.org/",
  "imageURI": "assets/protocols/ampleforth/logo.png",
  "chains": {
    "mainnet": {
      "auctionCreators": [
        "0xd8461BD73F19E3d789Ac0E5dbF1AD62FBBd15C22"
      ],
      "bondCreators": [
        "0xd8461BD73F19E3d789Ac0E5dbF1AD62FBBd15C22"
      ]
    },
    "goerli": {
      "auctionCreators": [
      ],
      "bondCreators": [
      ]
    }
  },
  "overrides": {
    "0xd8461BD73F19E3d789Ac0E5dbF1AD62FBBd15C22": {
      "name": "Ampleforth: Deployer"
    }
  }
}

=== buttonwood-protocol/buttonwood-protocol-list/src/protocolDefinitions/prl.json
{
  "name": "PRL",
  "homepage": "https://www.prl.one/",
  "imageURI": "assets/protocols/prl/mascot.png",
  "chains": {
    "mainnet": {
      "auctionCreators": [
        "0xd7e86Bd77784217324b4E94AEDc68E5C8227EC2B"
      ],
      "bondCreators": [
        "0xd7e86Bd77784217324b4E94AEDc68E5C8227EC2B"
      ]
    },
    "goerli": {
      "auctionCreators": [
        "0xfD99d2d103b09F95c3dFc458F57178bF0CD587B1",
        "0xEDBcCA5DfD692bab7656Ab2D4F499B43fA26480B",
        "0xb1Cc73B1610863D51B5b8269b9162237e87679c3"
      ],
      "bondCreators": [
        "0xfD99d2d103b09F95c3dFc458F57178bF0CD587B1",
        "0xEDBcCA5DfD692bab7656Ab2D4F499B43fA26480B",
        "0xb1Cc73B1610863D51B5b8269b9162237e87679c3"
      ]
    }
  }
}
